spring:
  application:
    name: boardProject

  datasource:
    url: jdbc:mysql://localhost:3306/boardProject
    username: yoon
    password: 12qwaszx!@
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80